module.exports = {
    products: [
        {
            _id: '1',
            name: 'Tshort sinza',
            category: 'vestuario',
            image: '/images/product-1.jpg',
            price: 2000,
            brand: 'HiskWins',
            rating: 4.5,
            numRewiews: 10,
            conuntInStock: 6,
        },
        {
            _id: '2',
            name: 'Tshort sinza',
            category: 'vestuario',
            image: '/images/product-6.jpg',
            price: 2000,
            brand: 'HiskWins',
            rating: 4.5,
            numRewiews: 10,
            conuntInStock: 6,
        },
        {
            _id: '3',
            name: 'Tshort sinza',
            category: 'vestuario',
            image: '/images/product-2.jpg',
            price: 2000,
            brand: 'HiskWins',
            rating: 4.5,
            numRewiews: 10,
            conuntInStock: 6,
        },
        {
            _id: '4',
            name: 'Tshort sinza',
            category: 'vestuario',
            image: '/images/product-3.jpg',
            price: 2000,
            brand: 'HiskWins',
            rating: 4.5,
            numRewiews: 10,
            conuntInStock: 6,
        },
        {
            _id: '5',
            name: 'Tshort sinza',
            category: 'vestuario',
            image: '/images/product-4.jpg',
            price: 2000,
            brand: 'HiskWins',
            rating: 4.5,
            numRewiews: 10,
            conuntInStock: 6,
        },
        {
            _id: '6',
            name: 'Tshort sinza',
            category: 'vestuario',
            image: '/images/product-5.jpg',
            price: 2000,
            brand: 'HiskWins',
            rating: 4.5,
            numRewiews: 10,
            conuntInStock: 6,
        },

    ]
}